# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-10 02:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pmessages", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proxymessage",
            name="message",
            field=models.CharField(max_length=500),
        ),
    ]
