# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-11 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pmessages", "0003_proxymessage_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proxymessage",
            name="date",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="proxymessage",
            name="username",
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="proxyuser",
            name="username",
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
