# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-06 09:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pmessages', '0004_auto_20181011_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxymessage',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pmessages.ProxyUser'),
        ),
    ]
