# Generated by Django 2.2.12 on 2020-11-08 22:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("pmessages", "0008_auto_20201108_2304"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proxyuser",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
